<ips:template parameters="$form" />
<div class="acpBlock ipsSpacer_bottom">
    <p class="acpBlock_title">Instructions</p>
    <div class="ipsPadding_horizontal">
        <h4>Prevent PERSCOM.io from sending emails</h4>
        <ol>
            <li>On PERSCOM.io go to "System" > "Settings",</li>
            <li>Navigate to "Registration" tab,</li>
            <li>Turn off "Admin Approval Required".</li>
        </ol>
    </div>
</div>
{$form|raw}
